name: Auto Create Pull Request

on:
  push:
    branch: develop

jobs:
  pull_request:
    name: Create Pull Request to main
    runs-on: ubuntu-latest

    steps:
      - name: Create Pull Request
        uses: actions/github-script@v4
        with:
          script: |
            const branch = context.ref.replace('refs/heads/','')

            const pr = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: branch,
              base: 'main',
              state: 'open',
            })
            console.log(pr.data.length)

            if (!pr.dath.length) {
              github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `${branch} to master`,
                head: branch,
                base: 'main'
              })
            }
