name: Auto Create Pull Request

on:
  push:
    branch: develop

jobs:
  pull_request:
    name: Create Pull Request to main
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: get-branch-name
        env:
          GITHUB_REF: ${{ github.ref }}
        run: echo '::set-output name=BRANCH_NAME::${GITHUB_REF#refs/heads/}',

      - name: Exist Pull Request
        id: exist-pull-request
        uses: actions/github-script@v4
        with:
          script: |
            return github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: ${{ steps.get-branch-name.outputs.BRANCH_NAME }},
              base: 'main',
              state: 'open',
            })

      - name: Create Pull Request
        if: fromJSON(steps.exist-pull-request.outputs.result).status != 200
        uses: actions/github-script@v4
        with:
          script: |
            return github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'develop to master',
              head: ${{ steps.get-branch-name.outputs.BRANCH_NAME }},
              base: 'main'
            })
